const {COLOR, SHAPE, GRADE, CLARITY, FLUORESCENCE} = require("../utils/consts");

const DIAMONDS_1 = [
  {
    number: 2446423766,
    date: 1660867200,
    shape: SHAPE.ROUND,
    length: 445,
    width: 453,
    depth: 290,
    points: 40,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS1,
    cut: GRADE.GOOD,
    polish: GRADE.EX,
    symmetry: GRADE.GOOD,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 2398641960,
    date: 1627344000,
    shape: SHAPE.ROUND,
    length: 452,
    width: 461,
    depth: 290,
    points: 40,
    color: COLOR.M,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VVS2,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.GOOD,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 2446359562,
    date: 1660608000,
    shape: SHAPE.ROUND,
    length: 446,
    width: 452,
    depth: 299,
    points: 40,
    color: COLOR.Q,
    toColor: COLOR.R,
    clarity: CLARITY.VS2,
    cut: GRADE.GOOD,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 2446378854,
    date: 1660694400,
    shape: SHAPE.ROUND,
    length: 456,
    width: 460,
    depth: 294,
    points: 40,
    color: COLOR.M,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.VG,
    polish: GRADE.VG,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 7448415330,
    date: 1554249600,
    shape: SHAPE.ROUND,
    length: 450,
    width: 456,
    depth: 301,
    points: 40,
    color: COLOR.M,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.GOOD,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 5446423776,
    date: 1660867200,
    shape: SHAPE.ROUND,
    length: 448,
    width: 454,
    depth: 298,
    points: 40,
    color: COLOR.Q,
    toColor: COLOR.R,
    clarity: CLARITY.VS2,
    cut: GRADE.GOOD,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 6322989281,
    date: 1559692800,
    shape: SHAPE.ROUND,
    length: 482,
    width: 486,
    depth: 305,
    points: 44,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VVS2,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 6312163094,
    date: 1541116800,
    shape: SHAPE.ROUND,
    length: 453,
    width: 458,
    depth: 301,
    points: 40,
    color: COLOR.M,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.GOOD,
    polish: GRADE.VG,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 2327419162,
    date: 1554249600,
    shape: SHAPE.ROUND,
    length: 450,
    width: 456,
    depth: 301,
    points: 40,
    color: COLOR.M,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.GOOD,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 7308251904,
    date: 1535155200,
    shape: SHAPE.ROUND,
    length: 453,
    width: 460,
    depth: 295,
    points: 40,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VVS1,
    cut: GRADE.VG,
    polish: GRADE.VG,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 5336407543,
    date: 1564704000,
    shape: SHAPE.ROUND,
    length: 470,
    width: 474,
    depth: 287,
    points: 40,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VS1,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 7331706894,
    date: 1568764800,
    shape: SHAPE.ROUND,
    length: 483,
    width: 487,
    depth: 303,
    points: 44,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VS2,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 1325127814,
    date: 1551398400,
    shape: SHAPE.ROUND,
    length: 494,
    width: 496,
    depth: 294,
    points: 43,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 6342643823,
    date: 1579737600,
    shape: SHAPE.ROUND,
    length: 481,
    width: 484,
    depth: 282,
    points: 40,
    color: COLOR.Q,
    toColor: COLOR.R,
    clarity: CLARITY.VVS2,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 2277565595,
    date: 1512518400,
    shape: SHAPE.ROUND,
    length: 468,
    width: 471,
    depth: 296,
    points: 40,
    color: COLOR.Q,
    toColor: COLOR.R,
    clarity: CLARITY.VS2,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 1288154225,
    date: 1518739200,
    shape: SHAPE.ROUND,
    length: 469,
    width: 472,
    depth: 292,
    points: 40,
    color: COLOR.Q,
    toColor: COLOR.R,
    clarity: CLARITY.VS2,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 6282442912,
    date: 1521072000,
    shape: SHAPE.ROUND,
    length: 460,
    width: 462,
    depth: 296,
    points: 40,
    color: COLOR.S,
    toColor: COLOR.T,
    clarity: CLARITY.VS1,
    cut: GRADE.GOOD,
    polish: GRADE.VG,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 2437719712,
    date: 1655251200,
    shape: SHAPE.ROUND,
    length: 471,
    width: 474,
    depth: 294,
    points: 40,
    color: COLOR.M,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 5426521085,
    date: 1646092800,
    shape: SHAPE.ROUND,
    length: 470,
    width: 471,
    depth: 295,
    points: 40,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS1,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 6365369799,
    date: 1603411200,
    shape: SHAPE.ROUND,
    length: 459,
    width: 461,
    depth: 297,
    points: 40,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VS2,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 2367369811,
    date: 1603497600,
    shape: SHAPE.ROUND,
    length: 477,
    width: 481,
    depth: 299,
    points: 42,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VS1,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 2436408283,
    date: 1652400000,
    shape: SHAPE.ROUND,
    length: 471,
    width: 473,
    depth: 298,
    points: 41,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VVS1,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 1228205558,
    date: 1459382400,
    shape: SHAPE.ROUND,
    length: 459,
    width: 464,
    depth: 294,
    points: 40,
    color: COLOR.M,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS1,
    cut: GRADE.GOOD,
    polish: GRADE.GOOD,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 7243666260,
    date: 1484006400,
    shape: SHAPE.ROUND,
    length: 473,
    width: 475,
    depth: 294,
    points: 40,
    color: COLOR.M,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VVS1,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: ,
    date: ,
    shape: SHAPE.ROUND,
    length: ,
    width: ,
    depth: ,
    points: ,
    color: COLOR.,
    toColor: COLOR.,
    clarity: CLARITY.,
    cut: GRADE.,
    polish: GRADE.,
    symmetry: GRADE.,
    fluorescence: FLUORESCENCE.,
  },
  {
    number: 2436909739,
    date: 1657756800,
    shape: SHAPE.ROUND,
    length: 470,
    width: 473,
    depth: 292,
    points: 40,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.IF,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 2437809988,
    date: 1655942400,
    shape: SHAPE.ROUND,
    length: 467,
    width: 470,
    depth: 295,
    points: 40,
    color: COLOR.M,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS1,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 5446023899,
    date: 1657670400,
    shape: SHAPE.ROUND,
    length: 467,
    width: 471,
    depth: 288,
    points: 40,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VVS1,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 2447023866,
    date: 1657756800,
    shape: SHAPE.ROUND,
    length: 468,
    width: 471,
    depth: 292,
    points: 40,
    color: COLOR.Q,
    toColor: COLOR.R,
    clarity: CLARITY.VVS1,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 6412023143,
    date: 1635465600,
    shape: SHAPE.ROUND,
    length: 458,
    width: 463,
    depth: 291,
    points: 40,
    color: COLOR.M,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.GOOD,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 7396690487,
    date: 1627862400,
    shape: SHAPE.ROUND,
    length: 447,
    width: 461,
    depth: 295,
    points: 40,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.GOOD,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 6391541032,
    date: 1626739200,
    shape: SHAPE.ROUND,
    length: 471,
    width: 474,
    depth: 295,
    points: 40,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VS1,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 1203455699,
    date: 1437523200,
    shape: SHAPE.ROUND,
    length: 473,
    width: 476,
    depth: 293,
    points: 40,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VVS2,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 6225398562,
    date: 1461024000,
    shape: SHAPE.ROUND,
    length: 455,
    width: 461,
    depth: 296,
    points: 40,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VS1,
    cut: GRADE.GOOD,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 2216235019,
    date: 1448582400,
    shape: SHAPE.ROUND,
    length: 469,
    width: 473,
    depth: 294,
    points: 40,
    color: COLOR.Q,
    toColor: COLOR.R,
    clarity: CLARITY.VS1,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 1223548955,
    date: 1462406400,
    shape: SHAPE.ROUND,
    length: 461,
    width: 464,
    depth: 297,
    points: 40,
    color: COLOR.Q,
    toColor: COLOR.R,
    clarity: CLARITY.VVS2,
    cut: GRADE.VG,
    polish: GRADE.VG,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 2416838644,
    date: 1641513600,
    shape: SHAPE.ROUND,
    length: 460,
    width: 467,
    depth: 297,
    points: 41,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.VG,
    polish: GRADE.VG,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 7431609079,
    date: 1654214400,
    shape: SHAPE.CUSHION,
    length: 421,
    width: 415,
    depth: 284,
    points: 40,
    color: COLOR.L,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VVS2,
    cut: GRADE.EMPTY,
    polish: GRADE.VG,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 1425183799,
    date: 1643846400,
    shape: SHAPE.ROUND,
    length: 487,
    width: 499,
    depth: 320,
    points: 50,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS1,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.GOOD,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 6422483459,
    date: 1645833600,
    shape: SHAPE.ROUND,
    length: 477,
    width: 488,
    depth: 320,
    points: 50,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VS1,
    cut: GRADE.GOOD,
    polish: GRADE.VG,
    symmetry: GRADE.GOOD,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 2427470873,
    date: 1645660800,
    shape: SHAPE.ROUND,
    length: 481,
    width: 488,
    depth: 319,
    points: 50,
    color: COLOR.Q,
    toColor: COLOR.R,
    clarity: CLARITY.VS2,
    cut: GRADE.GOOD,
    polish: GRADE.VG,
    symmetry: GRADE.GOOD,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 6442458622,
    date: 1661299200,
    shape: SHAPE.ROUND,
    length: 485,
    width: 491,
    depth: 316,
    points: 50,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.GOOD,
    polish: GRADE.VG,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 2347516586,
    date: 1578268800,
    shape: SHAPE.ROUND,
    length: 496,
    width: 499,
    depth: 318,
    points: 50,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS1,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 6392039873,
    date: 1623974400,
    shape: SHAPE.ROUND,
    length: 492,
    width: 498,
    depth: 319,
    points: 50,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 7382847221,
    date: 1622419200,
    shape: SHAPE.ROUND,
    length: 526,
    width: 530,
    depth: 337,
    points: 60,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS1,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 2386886319,
    date: 1622851200,
    shape: SHAPE.ROUND,
    length: 505,
    width: 509,
    depth: 308,
    points: 50,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VVS2,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.GOOD,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 6402471538,
    date: 1634688000,
    shape: SHAPE.ROUND,
    length: 495,
    width: 498,
    depth: 321,
    points: 50,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS1,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 1417591068,
    date: 1639180800,
    shape: SHAPE.ROUND,
    length: 494,
    width: 497,
    depth: 319,
    points: 50,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VS1,
    cut: GRADE.VG,
    polish: GRADE.EX,
    symmetry: GRADE.VG,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 6415167653,
    date: 1638921600,
    shape: SHAPE.ROUND,
    length: 516,
    width: 519,
    depth: 318,
    points: 52,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
  {
    number: 1413167693,
    date: 1638921600,
    shape: SHAPE.ROUND,
    length: 511,
    width: 515,
    depth: 316,
    points: 51,
    color: COLOR.O,
    toColor: COLOR.P,
    clarity: CLARITY.VS2,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.FAINT,
  },
  {
    number: 2417168388,
    date: 1638921600,
    shape: SHAPE.ROUND,
    length: 503,
    width: 507,
    depth: 315,
    points: 50,
    color: COLOR.N,
    toColor: COLOR.EMPTY,
    clarity: CLARITY.VS2,
    cut: GRADE.EX,
    polish: GRADE.EX,
    symmetry: GRADE.EX,
    fluorescence: FLUORESCENCE.NONE,
  },
];

module.exports = { DIAMONDS_1 };
